"""empty message

Revision ID: 2b4cfc3e5eda
Revises: 34b970a75ccc
Create Date: 2023-01-30 20:17:05.051196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b4cfc3e5eda'
down_revision = '34b970a75ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.alter_column('csr',
               existing_type=sa.TEXT(),
               type_=sa.LargeBinary(),
               existing_nullable=True)
        batch_op.alter_column('key',
               existing_type=sa.TEXT(),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.alter_column('key',
               existing_type=sa.LargeBinary(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('csr',
               existing_type=sa.LargeBinary(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
