"""certificates table

Revision ID: b863bae26507
Revises: fe5ed77ac081
Create Date: 2023-01-30 15:09:00.195281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b863bae26507'
down_revision = 'fe5ed77ac081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('csr',
               existing_type=sa.TEXT(),
               type_=sa.String(length=140),
               nullable=True)
        batch_op.alter_column('pfx',
               existing_type=sa.BLOB(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.alter_column('pfx',
               existing_type=sa.BLOB(),
               nullable=False)
        batch_op.alter_column('csr',
               existing_type=sa.String(length=140),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
