"""empty message

Revision ID: f9f64aba15a0
Revises: 07b0c0b43f13
Create Date: 2023-01-30 16:01:39.062083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9f64aba15a0'
down_revision = '07b0c0b43f13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cn', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('organization', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.drop_column('organization')
        batch_op.drop_column('cn')

    # ### end Alembic commands ###
